import { Doctor, Patient, Staff, Appointment, Prescription, Bill } from '@/types';

// ─── Mock Doctors ─────────────────────────────────────────────────────────────

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'd1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@medicare.com',
    phone: '5551012020',
    specialization: 'Cardiology',
    department: 'Cardiology',
    qualification: 'MD, FACC',
    experience: 12,
    status: 'active',
    appointmentsToday: 8,
    totalPatients: 142,
    joiningDate: '2015-03-10',
  },
  {
    id: 'd2',
    name: 'Dr. Michael Chen',
    email: 'michael.chen@medicare.com',
    phone: '5552023030',
    specialization: 'Neurology',
    department: 'Neurology',
    qualification: 'MD, PhD',
    experience: 15,
    status: 'active',
    appointmentsToday: 6,
    totalPatients: 198,
    joiningDate: '2012-07-22',
  },
  {
    id: 'd3',
    name: 'Dr. Emily Rodriguez',
    email: 'emily.rodriguez@medicare.com',
    phone: '5553034040',
    specialization: 'Pediatrics',
    department: 'Pediatrics',
    qualification: 'MD, FAAP',
    experience: 9,
    status: 'active',
    appointmentsToday: 10,
    totalPatients: 230,
    joiningDate: '2018-01-15',
  },
  {
    id: 'd4',
    name: 'Dr. James Wilson',
    email: 'james.wilson@medicare.com',
    phone: '5554045050',
    specialization: 'Orthopedics',
    department: 'Orthopedics',
    qualification: 'MD, FAAOS',
    experience: 20,
    status: 'on-leave',
    appointmentsToday: 0,
    totalPatients: 310,
    joiningDate: '2008-09-01',
  },
  {
    id: 'd5',
    name: 'Dr. Aisha Patel',
    email: 'aisha.patel@medicare.com',
    phone: '5555056060',
    specialization: 'Dermatology',
    department: 'Dermatology',
    qualification: 'MD, FAAD',
    experience: 7,
    status: 'active',
    appointmentsToday: 5,
    totalPatients: 180,
    joiningDate: '2020-04-12',
  },
];

// ─── Mock Staff ───────────────────────────────────────────────────────────────

export const MOCK_STAFF: Staff[] = [
  {
    id: 's1',
    name: 'Robert Kim',
    email: 'robert.kim@medicare.com',
    phone: '5556067070',
    role: 'Head Nurse',
    department: 'Emergency',
    status: 'active',
    joinDate: '2017-05-20',
  },
  {
    id: 's2',
    name: 'Linda Torres',
    email: 'linda.torres@medicare.com',
    phone: '5557078080',
    role: 'Receptionist',
    department: 'General',
    status: 'active',
    joinDate: '2019-11-03',
  },
  {
    id: 's3',
    name: 'Tom Brady',
    email: 'tom.brady@medicare.com',
    phone: '5558089090',
    role: 'Lab Technician',
    department: 'Radiology',
    status: 'active',
    joinDate: '2021-02-18',
  },
];

// ─── Mock Patients ────────────────────────────────────────────────────────────

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'p1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '5559091010',
    dateOfBirth: '1985-06-15',
    gender: 'male',
    bloodGroup: 'O+',
    address: '123 Main St, New York, NY 10001',
    emergencyContact: 'Jane Smith',
    emergencyPhone: '5559091011',
    registrationDate: '2023-01-10',
    status: 'active',
    assignedDoctorId: 'd1',
    assignedDoctorName: 'Dr. Sarah Johnson',
    insuranceProvider: 'BlueCross',
    insuranceNumber: 'BC-123456',
  },
  {
    id: 'p2',
    name: 'Maria Garcia',
    email: 'maria.garcia@email.com',
    phone: '5551112223',
    dateOfBirth: '1992-11-28',
    gender: 'female',
    bloodGroup: 'A+',
    address: '456 Oak Ave, Los Angeles, CA 90001',
    emergencyContact: 'Carlos Garcia',
    emergencyPhone: '5551112224',
    registrationDate: '2023-03-22',
    status: 'active',
    assignedDoctorId: 'd3',
    assignedDoctorName: 'Dr. Emily Rodriguez',
  },
  {
    id: 'p3',
    name: 'David Lee',
    email: 'david.lee@email.com',
    phone: '5552223334',
    dateOfBirth: '1978-04-03',
    gender: 'male',
    bloodGroup: 'B-',
    address: '789 Pine Rd, Chicago, IL 60601',
    emergencyContact: 'Susan Lee',
    emergencyPhone: '5552223335',
    registrationDate: '2022-08-15',
    status: 'active',
    assignedDoctorId: 'd2',
    assignedDoctorName: 'Dr. Michael Chen',
  },
  {
    id: 'p4',
    name: 'Sarah Williams',
    email: 'sarah.williams@email.com',
    phone: '5553334445',
    dateOfBirth: '2001-09-17',
    gender: 'female',
    bloodGroup: 'AB+',
    address: '321 Elm St, Houston, TX 77001',
    emergencyContact: 'Bob Williams',
    emergencyPhone: '5553334446',
    registrationDate: '2024-01-05',
    status: 'active',
  },
  {
    id: 'p5',
    name: 'Michael Brown',
    email: 'michael.brown@email.com',
    phone: '5554445556',
    dateOfBirth: '1955-12-30',
    gender: 'male',
    bloodGroup: 'O-',
    address: '654 Maple Dr, Phoenix, AZ 85001',
    emergencyContact: 'Alice Brown',
    emergencyPhone: '5554445557',
    registrationDate: '2021-06-28',
    status: 'inactive',
  },
];

// ─── Mock Appointments ────────────────────────────────────────────────────────

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    patientId: 'p1',
    patientName: 'John Smith',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Johnson',
    date: '2026-03-11',
    time: '09:00',
    duration: 30,
    type: 'consultation',
    status: 'completed',
    department: 'Cardiology',
    room: '101',
  },
  {
    id: 'a2',
    patientId: 'p2',
    patientName: 'Maria Garcia',
    doctorId: 'd3',
    doctorName: 'Dr. Emily Rodriguez',
    date: '2026-03-11',
    time: '10:30',
    duration: 30,
    type: 'follow-up',
    status: 'in-progress',
    department: 'Pediatrics',
    room: '205',
  },
  {
    id: 'a3',
    patientId: 'p3',
    patientName: 'David Lee',
    doctorId: 'd2',
    doctorName: 'Dr. Michael Chen',
    date: '2026-03-11',
    time: '11:00',
    duration: 45,
    type: 'routine-checkup',
    status: 'scheduled',
    department: 'Neurology',
    room: '302',
  },
  {
    id: 'a4',
    patientId: 'p4',
    patientName: 'Sarah Williams',
    doctorId: 'd5',
    doctorName: 'Dr. Aisha Patel',
    date: '2026-03-12',
    time: '14:00',
    duration: 20,
    type: 'consultation',
    status: 'scheduled',
    department: 'Dermatology',
    room: '108',
  },
  {
    id: 'a5',
    patientId: 'p1',
    patientName: 'John Smith',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Johnson',
    date: '2026-03-10',
    time: '15:00',
    duration: 30,
    type: 'follow-up',
    status: 'cancelled',
    department: 'Cardiology',
  },
];

// ─── Mock Prescriptions ───────────────────────────────────────────────────────

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx1',
    patientId: 'p1',
    patientName: 'John Smith',
    doctorId: 'd1',
    doctorName: 'Dr. Sarah Johnson',
    date: '2026-03-11',
    diagnosis: 'Hypertension',
    symptoms: ['High blood pressure', 'Mild headaches', 'Fatigue'],
    medications: [
      {
        name: 'Lisinopril',
        dosage: '10mg',
        frequency: 'Once daily',
        duration: '30 days',
        instructions: 'Take with or without food. Avoid potassium supplements.',
      },
      {
        name: 'Aspirin',
        dosage: '81mg',
        frequency: 'Once daily',
        duration: '30 days',
        instructions: 'Take with food.',
      },
    ],
    notes: 'Monitor blood pressure daily. Return if BP > 160/100.',
    followUpDate: '2026-04-11',
    status: 'active',
  },
  {
    id: 'rx2',
    patientId: 'p3',
    patientName: 'David Lee',
    doctorId: 'd2',
    doctorName: 'Dr. Michael Chen',
    date: '2026-02-20',
    diagnosis: 'Migraine',
    symptoms: ['Severe headaches', 'Nausea', 'Light sensitivity'],
    medications: [
      {
        name: 'Sumatriptan',
        dosage: '50mg',
        frequency: 'As needed (max 2/day)',
        duration: '14 days',
        instructions: 'Take at onset of migraine. Do not exceed 200mg/day.',
      },
    ],
    followUpDate: '2026-03-20',
    status: 'active',
  },
];

// ─── Mock Bills ───────────────────────────────────────────────────────────────

export const MOCK_BILLS: Bill[] = [
  {
    id: 'b1',
    patientId: 'p1',
    patientName: 'John Smith',
    appointmentId: 'a1',
    date: '2026-03-11',
    dueDate: '2026-03-25',
    items: [
      { description: 'Consultation Fee (Cardiology)', quantity: 1, unitPrice: 250, total: 250 },
      { description: 'ECG Test', quantity: 1, unitPrice: 120, total: 120 },
      { description: 'Blood Panel', quantity: 1, unitPrice: 85, total: 85 },
    ],
    subtotal: 455,
    tax: 45.5,
    discount: 0,
    total: 500.5,
    status: 'pending',
  },
  {
    id: 'b2',
    patientId: 'p3',
    patientName: 'David Lee',
    date: '2026-02-20',
    dueDate: '2026-03-06',
    items: [
      { description: 'Neurology Consultation', quantity: 1, unitPrice: 300, total: 300 },
      { description: 'MRI Scan', quantity: 1, unitPrice: 800, total: 800 },
    ],
    subtotal: 1100,
    tax: 110,
    discount: 50,
    total: 1160,
    status: 'paid',
    paymentMethod: 'insurance',
    paidDate: '2026-02-28',
  },
  {
    id: 'b3',
    patientId: 'p2',
    patientName: 'Maria Garcia',
    date: '2026-02-01',
    dueDate: '2026-02-15',
    items: [
      { description: 'Pediatrics Consultation', quantity: 1, unitPrice: 180, total: 180 },
      { description: 'Vaccination', quantity: 2, unitPrice: 60, total: 120 },
    ],
    subtotal: 300,
    tax: 30,
    discount: 0,
    total: 330,
    status: 'overdue',
  },
];
